# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TagSpaceTool(object):
    def setupUi(self, TagSpaceTool):
        TagSpaceTool.setObjectName("TagSpaceTool")
        TagSpaceTool.resize(1174, 733)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TagSpaceTool.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(TagSpaceTool)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fixButton = QtWidgets.QPushButton(TagSpaceTool)
        self.fixButton.setObjectName("fixButton")
        self.horizontalLayout.addWidget(self.fixButton)
        self.advancedMode = QtWidgets.QCheckBox(TagSpaceTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedMode.sizePolicy().hasHeightForWidth())
        self.advancedMode.setSizePolicy(sizePolicy)
        self.advancedMode.setChecked(True)
        self.advancedMode.setTristate(True)
        self.advancedMode.setObjectName("advancedMode")
        self.horizontalLayout.addWidget(self.advancedMode)
        self.resetButton = QtWidgets.QToolButton(TagSpaceTool)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(TagSpaceTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupTextEdit = QtWidgets.QGroupBox(self.splitter)
        self.groupTextEdit.setObjectName("groupTextEdit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupTextEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupTextEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.groupTreeView = QtWidgets.QGroupBox(self.splitter)
        self.groupTreeView.setObjectName("groupTreeView")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupTreeView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupTreeView)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.filterLine = QtWidgets.QLineEdit(self.groupTreeView)
        self.filterLine.setClearButtonEnabled(True)
        self.filterLine.setObjectName("filterLine")
        self.horizontalLayout_2.addWidget(self.filterLine)
        self.expandButton = QtWidgets.QToolButton(self.groupTreeView)
        self.expandButton.setObjectName("expandButton")
        self.horizontalLayout_2.addWidget(self.expandButton)
        self.colapseButton = QtWidgets.QToolButton(self.groupTreeView)
        self.colapseButton.setObjectName("colapseButton")
        self.horizontalLayout_2.addWidget(self.colapseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.treeView = QtWidgets.QTreeView(self.groupTreeView)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeView)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(TagSpaceTool)
        self.expandButton.clicked.connect(self.treeView.expandAll)
        self.colapseButton.clicked.connect(self.treeView.collapseAll)
        QtCore.QMetaObject.connectSlotsByName(TagSpaceTool)

    def retranslateUi(self, TagSpaceTool):
        _translate = QtCore.QCoreApplication.translate
        TagSpaceTool.setWindowTitle(_translate("TagSpaceTool", "Tag space tool"))
        self.fixButton.setText(_translate("TagSpaceTool", "Fix tags"))
        self.advancedMode.setText(_translate("TagSpaceTool", "Advanced mode"))
        self.resetButton.setText(_translate("TagSpaceTool", "Clean last path"))
        self.groupTextEdit.setTitle(_translate("TagSpaceTool", "Logs:"))
        self.groupTreeView.setTitle(_translate("TagSpaceTool", "Grouped:"))
        self.label.setText(_translate("TagSpaceTool", "Filter:"))
        self.expandButton.setText(_translate("TagSpaceTool", "<||>"))
        self.colapseButton.setText(_translate("TagSpaceTool", "|><|"))
from . import resources_rc
